apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-se
spec:
  hosts:
    - httpbin.org
  exportTo:
    - "*"
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - httpbin.org
---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: egressgateway-for-httpbin
#spec:
#  host: istio-egressgateway.istio-system.svc.cluster.local
#  subsets:
#    - name: httpbin
#---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-httpbin-through-egress-gateway
spec:
  hosts:
    - httpbin.org
  gateways:
    - istio-egressgateway
    - mesh
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
#            subset: httpbin
            port:
              number: 80
          weight: 100
    - match:
        - gateways:
            - istio-egressgateway
          port: 80
      route:
        - destination:
            host: httpbin.org
            port:
              number: 80
          weight: 100
#---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: allow-egress-to-istio-system-and-kube-dns
#spec:
#  podSelector: { }
#  policyTypes:
#    - Egress
#  egress:
#    - to:
#        - namespaceSelector: { }
#          podSelector:
#            matchLabels:
#              k8s-app: kube-dns
#      ports:
#        - port: 53
#          protocol: UDP
#    - to:
#        - namespaceSelector: { }
#          podSelector:
#            matchLabels:
#              app: istio-egressgateway
---

# allow-nothing, by default
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: auth-default
#  namespace: istio-system # it MUST be in istio-system
#spec:
#  {}

# shpod should be allowed to access httpbin.org
# but it is not
# k exec shpod -it -n shpod  -- bash
# curl http://httpbin.org/ip -v
# --> 403
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin-auth
  namespace: istio-system
#  namespace: shpod
spec:
#  selector:
#    matchLabels:
#      app: istio-egressgateway
  action: ALLOW
#  action: AUDIT
  rules:
    - from:
#        - source:
#            principals: ["cluster.local/ns/shpod/sa/shpod"]
        - source:
            namespaces: ["shpod"]
      to:
#        - operation:
#            methods: ["GET"]
#            paths: ["/ip"]
#        - operation:
#            methods: ["POST"]
#            paths: ["/data"]
#      when:
#        - key: request.auth.claims[iss]
#          values: ["http://httpbin.org"]
